import type { ClosetItem, ClosetItemFitStatus } from '@/types/closet';
import type { CreateLookInput, LookRequestResponse } from '@/types/look-request';
import type { LocalImageAsset, UploadedImageAsset, UploadedImageCategory } from '@/types/media';
import type { PersistedSession, Profile } from '@/types/profile';
import type { OutfitResult } from '@/types/style';

export type ApiError = {
  code: string;
  message: string;
};

export type ApiResponse<T> = {
  success: boolean;
  data: T | null;
  error: ApiError | null;
};

export type ProfileUpsertRequest = {
  profile: Profile;
  onboardingCompleted: boolean;
};

export type ProfileSessionResponse = PersistedSession;

export type GenerateOutfitsRequest = CreateLookInput & {
  requestId: string;
  variantMap?: Partial<Record<CreateLookInput['selectedTiers'][number], number>>;
  /** When set, only this tier is generated by OpenAI. selectedTiers is still stored as the full set. */
  generateOnlyTier?: CreateLookInput['selectedTiers'][number];
};

export type GenerateOutfitsResponse = LookRequestResponse;

export type AnalysisVerdict = 'Works great' | 'Works okay' | "Doesn't work";
export type StrengthLabel = 'Strong' | 'Moderate' | 'Weak';
export type FidelityLabel = 'Close' | 'Adjusted' | 'Different';

export type AnalysisResponse = {
  id?: string;
  verdict: AnalysisVerdict;
  // ── Compatibility (Check Outfit) ──────────────────────
  itemMatch?: StrengthLabel;
  outfitFit?: StrengthLabel;
  outfitImpact?: string[];
  // ── Selfie Review ─────────────────────────────────────
  lookFidelity?: FidelityLabel;
  overallLook?: StrengthLabel;
  substitutionImpact?: string[];
  // ── Shared ────────────────────────────────────────────
  summary?: string;
  // ── Legacy (kept for historical stored results) ───────
  explanation?: string;
  concerns?: string[];
  suggestedAlternatives?: string[];
  strengths?: string[];
  issues?: string[];
  recommendedAdjustments?: string[];
  stylistNotes: string[];
  suggestedChanges: string[];
  createdAt?: string;
};

export type OutfitHistoryResponse = {
  items: GenerateOutfitsResponse[];
  total: number;
  page: number;
  hasMore: boolean;
};

export type CompatibilityCheckRequest = {
  image: LocalImageAsset;
  uploadedImage?: UploadedImageAsset | null;
  requestId?: string;
  tier?: string;
  outfitTitle?: string;
  anchorItemDescription?: string;
  pieceName?: string;
  candidateItemDescription?: string;
};

export type CompatibilityCheckResponse = AnalysisResponse;

export type SelfieReviewRequest = {
  image: LocalImageAsset;
  uploadedImage?: UploadedImageAsset | null;
  requestId?: string;
  tier?: string;
  outfitTitle?: string;
  anchorItemDescription?: string;
};

export type UploadImageResponse = UploadedImageAsset;

export type DeleteUploadResponse = {
  deleted: boolean;
};

export type SelfieReviewResponse = AnalysisResponse;

export type AnalyzeClosetItemRequest = {
  uploadedImageId?: string;
  uploadedImageUrl?: string;
  sketchImageUrl?: string;
  description?: string;
};

export type AnalyzeClosetItemResponse = {
  title: string;
  category: string;
  brand?: string | null;
  subcategory?: string | null;
  primaryColor?: string | null;
  colorFamily?: string | null;
  material?: string | null;
  formality?: string | null;
  silhouette?: string | null;
  weight?: string | null;
  pattern?: string | null;
  lensShape?: string | null;
  frameColor?: string | null;
};

export type SaveClosetItemRequest = {
  title: string;
  brand: string;
  size: string;
  category: string;
  uploadedImageId?: string;
  uploadedImageUrl?: string;
  sketchImageUrl?: string;
  subcategory?: string;
  primaryColor?: string;
  colorFamily?: string;
  material?: string;
  formality?: string;
  silhouette?: string;
  season?: string;
  weight?: string;
  pattern?: string;
  notes?: string;
  fitStatus?: ClosetItemFitStatus;
  lensShape?: string;
  frameColor?: string;
};

export type GetClosetItemsResponse = {
  items: ClosetItem[];
};

export type UpdateClosetItemRequest = {
  id: string;
  title: string;
  brand: string;
  size: string;
  category: string;
  subcategory?: string;
  primaryColor?: string;
  colorFamily?: string;
  material?: string;
  formality?: string;
  silhouette?: string;
  season?: string;
  weight?: string;
  pattern?: string;
  notes?: string;
  fitStatus?: ClosetItemFitStatus;
  lensShape?: string;
  frameColor?: string;
};

export type GenerateClosetSketchRequest = {
  uploadedImageId?: string;
  uploadedImageUrl?: string;
  title?: string;
  category?: string;
  lensShape?: string;
  frameColor?: string;
};

export type GenerateClosetSketchResponse = {
  jobId: string;
};

export type GetClosetSketchResponse = {
  sketchStatus: 'pending' | 'ready' | 'failed';
  sketchImageUrl: string | null;
};

export type SecondOpinionRequest = {
  stylistId: 'vittorio' | 'alessandra';
  profileId?: string;
  outfitTitle?: string;
  tier?: string;
  anchorItem?: string;
  keyPieces?: string[];
  shoes?: string[];
  accessories?: string[];
  fitNotes?: string[];
  whyItWorks?: string;
  stylingDirection?: string;
};

export type SecondOpinionResponse = {
  id: string;
  stylistId: 'vittorio' | 'alessandra';
  perspective: string;
  createdAt: string;
};

/** Structured outfit piece input for the closet matching API. */
export type OutfitPieceInput = {
  display_name: string;
  /** Canonical category from OutfitPieceCategory enum — used as a hard matching gate. */
  category?: string;
  color?: string;
  formality?: string;
};

export type ClosetMatchRequest = {
  suggestions: OutfitPieceInput[];
  items: { id: string; title: string; category: string; brand?: string; colorFamily?: string; material?: string; formality?: string; lensShape?: string }[];
  /** 0 = most forgiving, 100 = most precise. Default: 50. */
  sensitivity?: number;
  /** Item IDs to exclude — used when regenerating a specific slot after thumbs-down. */
  excludeItemIds?: string[];
};

export type ClosetMatchResponse = {
  matches: { suggestionIndex: number; suggestion: string; matchedItemId: string | null }[];
};

export type HelpMePickRequest = {
  stylistId: 'vittorio' | 'alessandra';
  dayType: string;
  vibe: string;
  risk: string;
  season?: string;
  rejectedIds?: string[];
};

export type HelpMePickResponse = {
  itemId: string;
  itemTitle: string;
  itemImageUrl: string | null;
  itemFitStatus: string | null;
  reason: string;
  stylistId: 'vittorio' | 'alessandra';
};

export type ClosetAnalyseRecommendation = {
  piece_name: string;
  reason: string;
  versatility_tags: string[];
  impact_score: number;
};

export type ClosetAnalyseStylist = {
  has_recommendations: boolean;
  no_gap_message: string;
  recommendations: ClosetAnalyseRecommendation[];
};

export type ClosetAnalyseResponse = {
  total_score: number;
  summary: string;
  sub_scores: {
    formality_range: number;
    color_versatility: number;
    seasonal_coverage: number;
    layering_options: number;
    occasion_coverage: number;
  };
  vittorio: ClosetAnalyseStylist;
  alessandra: ClosetAnalyseStylist;
};
